version: '3'
services:
  web:
    container_name: "go_docker"
    build: .
    links:
      - db_mysql
    volumes:
      - ".:${GOPATH}/Go_Docker/src/docker"
    env_file:
      - "./.env"
    ports:
      - "8080:8080"
    environment:
      WORKDIR: "${GOPATH}/Go_Docker/src/docker"

  db_mysql:
    image: mysql:5.7
    volumes:
      - "./db_data:/var/lib/mysql"
    restart: always
    ports:
      - "3307:3306"